# nixpacks.toml
# Configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
    "npm run build",
    "npm run prisma:generate"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
